### ISSUE TITLE
Selected ISO is forgotten after dongle removal 

### ISSUE THREAD

**Issue by asilvan** [openSX70/openSX70-Arduino-main#18]
## Bug Description 
When AUTO ISO 125 (SX-70 film) is selected in the Dongle and then the dongle is removed, the subsequent photos will use AUTO ISO 600 .
## How to Reproduce
1. Turn on the camera (unfold)
2. Insert the Dongle
3. Select Auto ISO 125 in the Dongle
4. Remove the Dongle
5. Take a picture

**Expected behavior**
Photo should be taken using Auto ISO 125
**Actual behavior**
Photo is taken using Auto ISO 600. Debug log shows :
```
take a picture on Auto Mode with ISO: 640, current Picture: 4
```
## Environment
**Hardware Details**
Camera Model: SX-70 Sonar
Board Version: 20200629 Sonar FBW-2
Dongle Version: uDongle 6.6 SP 20200229
Sensor Type: TCS3200
 
**Build details**
Using last commit in master (981e584185eff78d8437df7680bb76380d4f859b)

**Comment by a0727963** [comment]
Its not a bug... You have to save the ISO to the eeprom if u like to change the iso.... both switches on select the desired iso and insert the dongle... the led should blink redDipl. -Ing. Hannes Stornig
-------- Ursprüngliche Nachricht --------Von: Abel Silva ***@***.***> Datum: 15.08.21  02:13  (GMT+01:00) An: openSX70/openSX70-Arduino-main ***@***.***> Cc: Subscribed ***@***.***> Betreff: [openSX70/openSX70-Arduino-main] Selected ISO is forgotten after
  dongle removal  (#18) 
Bug Description
When AUTO ISO 125 (SX-70 film) is selected in the Dongle and then the dongle is removed, the subsequent photos will use AUTO ISO 600 .
How to Reproduce
Steps to reproduce the behavior:

Turn on the camera (unfold)
Insert the Dongle
Select Auto ISO 125 in the Dongle
Remove the Dongle
Take a picture

Expected behavior
Photo should be taken using Auto ISO 125
Actual behavior
Photo is taken using Auto ISO 600. Debug log shows :
take a picture on Auto Mode with ISO: 640, current Picture: 4

Environment
Hardware Details
Camera Model: SX-70 Sonar
Board Version: 20200629 Sonar FBW-2
Dongle Version: uDongle 6.6 SP 20200229
Sensor Type: TCS3200
Build details
Using last commit in master (981e584)

**Comment by zanepollard** [comment]
Not a bug. ISO swapping is held in another function entirely in order to preserve write cycles to the EEPROM as well as prevent accidental ISO switching. 

Solution would be for me to update the wiki and make the ISO swapping via dongle insertion more clear.
